### ISSUE TITLE
Option to create a new task

### ISSUE THREAD

**Issue by borouhin** [Ruvin/Conscious-ClickUp-Thunderbird-Plugin#2]
Hi! Thanks for the add-on, it's really helpful.

But it would be nice if the add-on could not just attack comments to existing tasks, but instead **create** new tasks in ClickUp (adding comment like it does currently afterwards).
This requires adding some extra UI elements like task name (should default to mail subject), start/end date and optionally/later other task fields, but it will speed up the work significantly.

Thanks in advance. If possible, tell if you plan to develop this add-on further or not. If not - maybe I'll try to fork the project and implement this myself.

**Comment by Ruvin** [comment]
thanks.
new version of add-on has been released:
https://github.com/Ruvin/Conscious-ClickUp-Thunderbird-Plugin/releases/tag/v2.0.0
