### ISSUE TITLE
Upload the add-on to addons.thunderbird.net

### ISSUE THREAD

**Issue by borouhin** [Ruvin/Conscious-ClickUp-Thunderbird-Plugin#4]
IMHO, adding the add-on to official TB repository will attract many more users and help to boost development.
I myself had been searching "ClickUp" among TB add-ons every few months for a long time with no result, until I accidentally found this project.

**Comment by Ruvin** [comment]
thank you for the suggestion.
the add-on has been published on the official TB repository.
https://addons.thunderbird.net/en-US/thunderbird/addon/conscious-clickup-save/
